"""
Tests to ensure all UI elements are properly connected to their configuration options.

This test file verifies that UI elements generated by PluginUIGenerator 
are properly connected to their corresponding configuration options.
"""

import pytest
import sys
import os

# Ensure project root is in path
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__)))))

# Try to import PyQt6, skip tests if not available
try:
    from PyQt6.QtWidgets import QApplication
    from interface.ui.plugin_ui_generator import PluginUIGenerator
    from plugin_config import ConfigField, PluginConfigMixin
    from convert_to_csv import CsvConverter
    from ftp_backend import FTPSendBackend
    from email_backend import EmailSendBackend
    
    PYQT6_AVAILABLE = True
except ImportError:
    PYQT6_AVAILABLE = False

pytestmark = pytest.mark.skipif(not PYQT6_AVAILABLE, reason="PyQt6 not available")


@pytest.fixture
def qapp():
    """Create QApplication for tests."""
    app = QApplication.instance()
    if app is None:
        app = QApplication(sys.argv)
    yield app


class TestUIElementConnection:
    """Tests to ensure all UI elements are properly connected to their configuration options."""

    def test_ui_generation_matches_config_fields(self, qapp):
        """Test that UI elements generated match the configuration fields defined."""
        # Define a plugin with various config fields
        class TestPlugin(PluginConfigMixin):
            PLUGIN_ID = "test_ui"
            PLUGIN_NAME = "Test UI Connection"
            CONFIG_FIELDS = [
                ConfigField(key="string_opt", label="String Option", type="string", default="default_str"),
                ConfigField(key="bool_opt", label="Boolean Option", type="boolean", default=True),
                ConfigField(key="int_opt", label="Integer Option", type="integer", default=42, min_value=0, max_value=100),
                ConfigField(key="float_opt", label="Float Option", type="float", default=3.14, min_value=0.0, max_value=10.0),
                ConfigField(key="select_opt", label="Select Option", type="select", 
                           options=["option1", "option2", "option3"], default="option2"),
                ConfigField(key="text_opt", label="Text Option", type="text", default="multiline\ntext"),
            ]
        
        # Generate UI for this plugin
        fields = TestPlugin.get_config_fields()
        widget, value_getters = PluginUIGenerator.create_plugin_config_widget(fields)
        
        # Verify that all config field keys have corresponding value getters
        field_keys = [field.key for field in fields]
        getter_keys = list(value_getters.keys())
        
        assert set(field_keys) == set(getter_keys), \
            f"Mismatch between config fields and UI value getters: {set(field_keys) ^ set(getter_keys)}"

    def test_ui_value_extraction_consistency(self, qapp):
        """Test that UI values extracted match the original configuration values."""
        # Define test configuration
        test_config = {
            "string_opt": "test string",
            "bool_opt": True,
            "int_opt": 123,
            "float_opt": 2.71,
            "select_opt": "option3",
            "text_opt": "multi\nline\ntext",
        }
        
        # Define matching config fields
        fields = [
            ConfigField(key="string_opt", label="String Option", type="string", default="default_str"),
            ConfigField(key="bool_opt", label="Boolean Option", type="boolean", default=False),
            ConfigField(key="int_opt", label="Integer Option", type="integer", default=0, min_value=0, max_value=1000),
            ConfigField(key="float_opt", label="Float Option", type="float", default=0.0, min_value=0.0, max_value=10.0),
            ConfigField(key="select_opt", label="Select Option", type="select", 
                       options=["option1", "option2", "option3"], default="option1"),
            ConfigField(key="text_opt", label="Text Option", type="text", default="default"),
        ]
        
        # Create UI with current values
        widget, value_getters = PluginUIGenerator.create_plugin_config_widget(
            fields, current_values=test_config
        )
        
        # Extract values back from UI
        extracted_values = PluginUIGenerator.get_config_values(value_getters)
        
        # Check that extracted values match original (with tolerance for type conversion)
        for key, original_value in test_config.items():
            extracted_value = extracted_values[key]
            assert type(original_value) == type(extracted_value), \
                f"Type mismatch for {key}: {type(original_value)} != {type(extracted_value)}"
            assert original_value == extracted_value, \
                f"Value mismatch for {key}: {original_value} != {extracted_value}"

    def test_all_plugin_types_have_connected_ui_elements(self, qapp):
        """Test that all plugin types have properly connected UI elements."""
        # Test CSV converter UI generation
        csv_fields = CsvConverter.get_config_fields()
        csv_widget, csv_getters = PluginUIGenerator.create_plugin_config_widget(csv_fields)
        
        # Verify all CSV config fields have corresponding UI elements
        csv_field_keys = [f.key for f in csv_fields]
        csv_getter_keys = list(csv_getters.keys())
        assert set(csv_field_keys) == set(csv_getter_keys)
        
        # Test FTP backend UI generation
        ftp_fields = FTPSendBackend.get_config_fields()
        ftp_widget, ftp_getters = PluginUIGenerator.create_plugin_config_widget(ftp_fields)
        
        # Verify all FTP config fields have corresponding UI elements
        ftp_field_keys = [f.key for f in ftp_fields]
        ftp_getter_keys = list(ftp_getters.keys())
        assert set(ftp_field_keys) == set(ftp_getter_keys)
        
        # Test email backend UI generation
        email_fields = EmailSendBackend.get_config_fields()
        email_widget, email_getters = PluginUIGenerator.create_plugin_config_widget(email_fields)
        
        # Verify all email config fields have corresponding UI elements
        email_field_keys = [f.key for f in email_fields]
        email_getter_keys = list(email_getters.keys())
        assert set(email_field_keys) == set(email_getter_keys)

    def test_conditional_field_visibility_handling(self, qapp):
        """Test that conditional fields (visible_if) are properly handled."""
        # Define fields with conditional visibility
        fields = [
            ConfigField(key="main_toggle", label="Main Toggle", type="boolean", default=False),
            ConfigField(key="conditional_field", label="Conditional", type="string", default="",
                       visible_if={"main_toggle": True}),
        ]
        
        # Create UI - conditional field should be skipped
        widget, value_getters = PluginUIGenerator.create_plugin_config_widget(fields)
        
        # Only the main toggle should have a getter (the conditional field is skipped due to visible_if)
        assert "main_toggle" in value_getters
        # Note: Currently the plugin UI generator skips fields with visible_if, so conditional_field won't have a getter
        # This is the expected behavior based on the current implementation
        
        # Verify that the visible_if field is not in the getters
        assert "conditional_field" not in value_getters

    def test_ui_modification_updates_values(self, qapp):
        """Test that modifying UI elements updates the extracted values."""
        # Create UI for a simple plugin
        fields = [
            ConfigField(key="test_field", label="Test Field", type="string", default="initial"),
        ]
        
        widget, value_getters = PluginUIGenerator.create_plugin_config_widget(fields)
        
        # Get initial value
        initial_values = PluginUIGenerator.get_config_values(value_getters)
        assert initial_values["test_field"] == "initial"
        
        # Get the actual widget
        from PyQt6.QtWidgets import QLineEdit
        # Find the QLineEdit widget in the layout
        line_edit_widgets = widget.findChildren(QLineEdit)
        assert len(line_edit_widgets) > 0, "Should have found a QLineEdit widget"
        
        # Update the widget value
        line_edit = line_edit_widgets[0]
        line_edit.setText("updated_value")
        
        # Get updated values
        updated_values = PluginUIGenerator.get_config_values(value_getters)
        assert updated_values["test_field"] == "updated_value"

    def test_complex_config_fields_mapping(self, qapp):
        """Test mapping for complex configuration fields."""
        # Test with a mix of field types and constraints
        fields = [
            ConfigField(key="bounded_int", label="Bounded Int", type="integer", 
                       default=50, min_value=0, max_value=100),
            ConfigField(key="bounded_float", label="Bounded Float", type="float", 
                       default=5.5, min_value=1.0, max_value=10.0),
            ConfigField(key="select_with_tuples", label="Select Tuples", type="select",
                       options=[("opt1", "Option 1"), ("opt2", "Option 2")], default="opt1"),
        ]
        
        widget, value_getters = PluginUIGenerator.create_plugin_config_widget(fields)
        
        # Check that all fields have getters
        for field in fields:
            assert field.key in value_getters, f"Missing getter for field: {field.key}"
        
        # Extract values and verify they match defaults
        values = PluginUIGenerator.get_config_values(value_getters)
        assert values["bounded_int"] == 50
        assert values["bounded_float"] == 5.5  # Float default
        assert values["select_with_tuples"] == "opt1"


if __name__ == "__main__":
    pytest.main([__file__, "-v"])